//! The decode table: every instruction group the Zig core knows, in the order
//! the decoder tries them.
//!
//! This is the one registration point. A group is a file under
//! src/core/cpu/ops/ holding a `pub const group: op.Group`, plus one line in
//! this list. Groups must not claim each other's encodings; the first one that
//! answers wins, so an overlap is a bug in the group, not an ordering choice.
const op = @import("../op.zig");

pub const groups = [_]op.Group{
    @import("hint.zig").group,
    @import("barrier.zig").group,
    @import("push_pop.zig").group,
    @import("sp_arith.zig").group,
    @import("ldr_literal.zig").group,
    @import("ldst_imm.zig").group,
    @import("ldst_reg.zig").group,
    @import("ldm_stm.zig").group,
    @import("shift_imm.zig").group,
    @import("add_sub.zig").group,
    @import("dp_reg.zig").group,
    @import("special_data.zig").group,
    @import("cps.zig").group,
    @import("cbz.zig").group,
    @import("extend.zig").group,
    @import("reverse.zig").group,
    @import("it.zig").group,
    @import("branch.zig").group,
    @import("mov_wide.zig").group,
    @import("divide.zig").group,
    @import("dp_shifted.zig").group,
    @import("shift_reg.zig").group,
    @import("add_sub_wide.zig").group,
    @import("long_mul.zig").group,
    @import("mrs_msr.zig").group,
    @import("ldst_reg_wide.zig").group,
    @import("bitfield.zig").group,
    @import("mul_acc.zig").group,
    @import("saturate.zig").group,
    @import("misc_wide.zig").group,
    @import("extend_wide.zig").group,
    @import("pkh.zig").group,
    @import("parallel.zig").group,
    @import("sel.zig").group,
    @import("sat_arith.zig").group,
    @import("extend_b16.zig").group,
    @import("sat16.zig").group,
    @import("usad8.zig").group,
    @import("umaal.zig").group,
    @import("dsp_mul16.zig").group,
    @import("dsp_dual.zig").group,
    @import("csel.zig").group,
    @import("long_shift.zig").group,
    @import("svc.zig").group,
    @import("table_branch.zig").group,
    @import("blxns.zig").group,
    @import("imm_logic.zig").group,
    @import("imm_arith.zig").group,
    @import("branch_wide.zig").group,
    @import("ldst_wide.zig").group,
    @import("ldr_literal_wide.zig").group,
    @import("fp_arith.zig").group,
    @import("fp_unary.zig").group,
    @import("fp_system.zig").group,
    @import("fp_convert.zig").group,
    @import("fp_directed.zig").group,
    @import("fp_move.zig").group,
    @import("fp_mem.zig").group,
    @import("mve_vpst.zig").group,
    @import("mve_int.zig").group,
    @import("mve_int_pair.zig").group,
    @import("mve_int_shift.zig").group,
    @import("mve_int_mulh.zig").group,
    @import("mve_int_vmla.zig").group,
    @import("mve_int_scalar.zig").group,
    @import("mve_vcmp.zig").group,
    @import("mve_vpred.zig").group,
    @import("mve_vdup.zig").group,
    @import("mve_lane_move.zig").group,
    @import("mve_lane_pair.zig").group,
    @import("mve_vmaxv.zig").group,
    @import("mve_int_vqdmlah.zig").group,
    @import("mve_vldr.zig").group,
    @import("mve_vldr_wide.zig").group,
    @import("ldrd_strd.zig").group,
    @import("exclusive.zig").group,
    @import("ldm_stm_wide.zig").group,
};
