//! Tests for src/periph/esp_hosted/esp_scan.zig.
//!
//! The expected bytes are generated by the model from the v2.12.12 proto,
//! not taken from a bench capture (RA8EMU-599 stays open for that).
const std = @import("std");
const ra8 = @import("ra8");
const hosted = ra8.periph.esp_hosted;
const event = hosted.event;
const frame = hosted.frame;
const scan = hosted.scan;
const station = hosted.station;

/// wifi_ap_record: bssid, ssid "benc", primary 6, rssi -55 sign-extended.
const ap_record = [_]u8{
    0x0A, 6,    2,    3,    4,    5,    6,    7,
    0x12, 4,    'b',  'e',  'n',  'c',  0x18, 6,
    0x28, 0xC9, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0x01,
};

fn bodyOf(id: u32, buf: []u8) ![]const u8 {
    var w: event.Writer = .{ .buf = buf };
    try std.testing.expect(try station.body(&w, id));
    return w.written();
}

test "ScanStart is acknowledged with an empty body" {
    var buf: [64]u8 = undefined;
    try std.testing.expectEqual(@as(usize, 0), (try bodyOf(scan.Id.req_start, &buf)).len);
}

test "ScanStart is followed by the scan-done event" {
    try std.testing.expectEqual(scan.Id.event_done, station.followUp(scan.Id.req_start).?);
}

test "ScanGetApNum answers one access point" {
    var buf: [64]u8 = undefined;
    try std.testing.expectEqualSlices(u8, &[_]u8{ 0x10, 1 }, try bodyOf(scan.Id.req_ap_num, &buf));
}

test "ScanGetApRecords answers the scripted AP record" {
    var buf: [64]u8 = undefined;
    const want = [_]u8{ 0x10, 1, 0x1A, ap_record.len } ++ ap_record;
    try std.testing.expectEqualSlices(u8, &want, try bodyOf(scan.Id.req_ap_records, &buf));
}

test "StaScanDone reports success with one result" {
    var buf: [16]u8 = undefined;
    var w: event.Writer = .{ .buf = &buf };
    try station.eventBody(&w, scan.Id.event_done);
    try std.testing.expectEqualSlices(u8, &[_]u8{ 0x12, 2, 0x10, 1 }, w.written());
}

test "each scan request gets a response frame and the event a frame" {
    var out: [frame.frame_size]u8 = undefined;
    for ([_]u32{ scan.Id.req_start, scan.Id.req_ap_num, scan.Id.req_ap_records }) |id| {
        try std.testing.expect(try hosted.rpc.answerFrame(&out, .{ .id = id, .uid = 7 }));
        try std.testing.expectEqual(frame.Interface.serial, (try frame.parse(&out)).header.interface);
    }
    try station.eventFrame(&out, scan.Id.event_done);
    try std.testing.expectEqual(frame.Interface.serial, (try frame.parse(&out)).header.interface);
}
