//! The M85 MVE (Helium) semantics, one namespace so root.zig carries a
//! single line for them: pure functions over Q registers and VPR, with
//! their vectors (RA8EMU-25, RA8EMU-23).
pub const qreg = @import("qreg.zig");
pub const predicate = @import("predicate.zig");
pub const vpt = @import("vpt.zig");
pub const int = @import("int.zig");
pub const int_vectors = @import("int_vectors.zig");
pub const int_shift = @import("int_shift.zig");
pub const int_shift_vectors = @import("int_shift_vectors.zig");
pub const int_width = @import("int_width.zig");
pub const int_width_vectors = @import("int_width_vectors.zig");
pub const int_insert = @import("int_insert.zig");
pub const int_insert_vectors = @import("int_insert_vectors.zig");
pub const reduce = @import("reduce.zig");
pub const reduce_vectors = @import("reduce_vectors.zig");
pub const reduce_minmax = @import("reduce_minmax.zig");
pub const reduce_minmax_vectors = @import("reduce_minmax_vectors.zig");
pub const int_mul = @import("int_mul.zig");
pub const int_mul_vectors = @import("int_mul_vectors.zig");
pub const compare = @import("compare.zig");
pub const compare_vectors = @import("compare_vectors.zig");
pub const bit_reverse = @import("bit_reverse.zig");
pub const bit_reverse_vectors = @import("bit_reverse_vectors.zig");
pub const contiguous = @import("contiguous.zig");
pub const contiguous_vectors = @import("contiguous_vectors.zig");
pub const contiguous_wide_vectors = @import("contiguous_wide_vectors.zig");
pub const gather = @import("gather.zig");
pub const gather_vectors = @import("gather_vectors.zig");
pub const gather64_vectors = @import("gather64_vectors.zig");
pub const gather_imm_vectors = @import("gather_imm_vectors.zig");
